apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 80           # Port externe
      targetPort: 8080    # Port interne du conteneur
  type: LoadBalancer     # Type LoadBalancer pour exposer l'application
