apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80           # Port exposé par le service
      targetPort: 8080   # Assure-toi que c'est bien celui du conteneur
  type: LoadBalancer
  sessionAffinity: None  # Facultatif, mais explicite
