name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Installer Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      # Étape 3 : Initialiser Terraform
      - name: Terraform Init
        run: terraform init

      # Étape 4 : Planifier les modifications
      - name: Terraform Plan
        run: terraform plan

      # Étape 5 : Appliquer les modifications (automatique ou manuel)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}